version: "3.7"

services:
  swarmops:
    container_name: swarmops
    image: blesswinsamuel/swarm-operator:latest
    build: .
    command:
      - --git-repo=git@github.com:blesswinsamuel/swarm-stack-example.git
      - --git-branch=master
      - --private-key-file=/root/.ssh/id_rsa
      - --repo-dir=/data/repo
      - --stack-file=stack.dev.yaml
      - --sync-interval=5m
      - --port=8080
    volumes:
      - ~/.ssh/:/root/.ssh/
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  swarmops_keys:
